development:
 adapter: postgresql
 encoding: unicode
 database: radio_development
 pool: 5
 username: refusion
 password: 123456

test:
 adapter: postgresql
 encoding: unicode
 database: radio_test
 pool: 5
 username: refusion
 password: 123456

production:
 adapter: postgresql
 encoding: unicode
 database: radio_production
 pool: 5
 username: refusion
 password: 123456